apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-15-tata
  namespace: fleet-local
spec:
  selector:
    matchLabels:
      app: odoo-15-tata
      tier: odoo-15-tata
  replicas: 3
  template:
    metadata:
      labels:
        app: odoo-15-tata
        tier: odoo-15-tata
    spec:
      containers:
      - name: odoo-15-tata
        env:
          - name: HOST
            value: 10.10.6.163
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
        image: odoo:15.0
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8069
          name: http
        - containerPort: 8072
          name: longpooling